# version: '3.8'

# services:
#   n8n:
#     image: n8nio/n8n
#     ports:
#       - "5678:5678"
#     volumes:
#       - D:/podcast_automation:/files
#       - D:/podcast_automation/n8n_data:/home/node/.n8n
#     depends_on:
#       - python-runner
#     networks:
#       - n8n_net

#   python-runner:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     volumes:
#       - D:/podcast_automation:/files
#     networks:
#       - n8n_net
#     environment:
#       - FLASK_ENV=development

# networks:
#   n8n_net:















version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - D:/podcast_automation:/files
      - D:/podcast_automation/n8n_data:/home/node/.n8n
    depends_on:
      - python-runner
    networks:
      - n8n_net

  python-runner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - D:/podcast_automation:/files
    networks:
      - n8n_net
    environment:
      - FLASK_ENV=development
    command: python /files/flask_generating_video.py

networks:
  n8n_net:
